server:
  port: 8000

spring:
  application:
    name: ms-registry

# 配置Eureka Server注册中心
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/