server:
  port: 8083 # 端口

spring:
  application:
    name: ms-seckill # 应用名
  # 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Itzler.666
    url: jdbc:mysql://127.0.0.1:3306/db_imooc?serverTimezone=Asia/Shanghai&character_set_server=utf8mb4&useUnicode=true&useSSL=false
  # Redis
  redis:
    port: 6379
    host: 127.0.0.1
    timeout: 3000

# Swagger
swagger:
  global-operation-parameters:
    - name:
  base-package: com.imooc.seckill
  title: 慕课美食社交食客API接口文档

# 配置 Eureka Server 注册中心
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

mybatis:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰映射

service:
  name:
    ms-oauth-server: http://ms-oauth2-server/

logging:
  pattern:
    console: '%d{HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n'
